<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-2L7QON7" failures="1" tests="1" name="AppTesting" time="0.182" errors="0" timestamp="2023-09-09T20:36:45 IST">
  <testcase classname="com.testng.demo.TestNGDemo1" name="testcase2" time="0.031">
    <failure type="java.lang.AssertionError" message="Failed testCase2">
      <![CDATA[java.lang.AssertionError: Failed testCase2
at com.testng.demo.TestNGDemo1.testcase2(TestNGDemo1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase classname="com.testng.demo.TestNGDemo1" name="testcase1" time="0.0">
    <ignored/>
  </testcase> <!-- testcase1 -->
  <testcase classname="com.testng.demo.TestNGDemo2" name="testcase3" time="0.0">
    <ignored/>
  </testcase> <!-- testcase3 -->
  <testcase classname="com.testng.demo.TestNGDemo2" name="testcase4" time="0.0">
    <ignored/>
  </testcase> <!-- testcase4 -->
</testsuite> <!-- AppTesting -->
